//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Bookings
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Please enter a valid status, Spaces and Numbers are not allowed")]
        public string status { get; set; }

        [Column(TypeName = "numeric")]
        public Nullable<int> price { get; set; }
        [Column(TypeName = "numeric")]
        public Nullable<int> rating { get; set; }
        public int UsersId { get; set; }
        public int FlightsId { get; set; }
    
        public virtual Users User { get; set; }
        public virtual Flights Flight { get; set; }
    }
}
