//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int seats { get; set; }
        public string status { get; set; }
        public int price { get; set; }
        public int rating { get; set; }
        public int FlightsId { get; set; }
    
        public virtual Flights Flight { get; set; }
    }
}
